### PR TITLE
Fix internal CI test failures

### LINKED ISSUE #745: Add tests in headless mode
Some CI environments are only able to run tests in headless mode.
We don't run tests in headless mode. Some of them are flaky or failing if forced to run in headless mode.

### PR DESCRIPTION
**Pull request by annagrin**
Chrome
- Add error logging to chrome launcher

Tests
- Add environment variable to detect headless-only mode (run by some CI)
- Run all tests in headless mode, if compatible
- Run all tests in normal mode if headless-only mode  is not detected
- Add waits and retries for some operations

Closes: https://github.com/dart-lang/tools/issues/745

### CODE REVIEW

File: lib/src/chrome.dart [hunk 1]
```diff
@@ -119,16 +122,23 @@ class Chrome {
...
+
+      await stderr
           .transform(utf8.decoder)
           .transform(const LineSplitter())
           .firstWhere((line) {
         errorLines.add(line);
         return line.startsWith('DevTools listening');
       }).timeout(const Duration(seconds: 60));
-    } catch (_) {
+    } catch (e, s) {
```
Comment (kevmoo) [inline lib/src/chrome.dart]: Is there a `TimeOut` exception or similar that we could catch explicitly and report back on.

Is 60s too long? Shouldn't it by pretty quick?

File: lib/src/chrome.dart [hunk 2]
```diff
@@ -46,6 +47,8 @@ String get _executable {
 
 /// Manager for an instance of Chrome.
 class Chrome {
+  static final _logger = Logger('CHROME');
```
Comment (kevmoo) [inline lib/src/chrome.dart]: Maybe make this a bit more explicit – like `browser_launcher.chrome`?

File: lib/src/chrome.dart (hunk 1 above)
Comment (annagrin) [reply lib/src/chrome.dart]: > Is 60s too long? Shouldn't it by pretty quick?

Maybe, but I am afraid to change that as this code is used in many slow CI systems... We keep finding timing failures (just like this PR shows).

Comment (annagrin) [reply lib/src/chrome.dart]: > Is there a TimeOut exception or similar that we could catch explicitly and report back on.

Will try that, thanks!

**Review by grouma — APPROVED** [review]

File: lib/src/chrome.dart (hunk 2 above)
Comment (annagrin) [reply lib/src/chrome.dart]: Done!

File: lib/src/chrome.dart (hunk 1 above)
Comment (annagrin) [reply lib/src/chrome.dart]: Done!
